## Normalisation

## 1. loading the cleaned dataset

In [1]:
import pandas as pd
import numpy as np

slqi_dataset = pd.read_csv("../Dataset/final_SLQI_dataset.csv")
slqi_dataset.head()

,Country,Country Code,gdp_per_capita,inflation,unemployment_rate,life_expectancy,secondary_enrollment,electricity_access,drinking_water_access,sanitation_access,government_effectiveness,political_stability,rule_of_law,forest_area,pm25_exposure,renewable_energy
0,Afghanistan,AFG,413.757895,-6.601186,13.6870,66.289,59.613602,85.3,80.832437,54.495799,-1.933997,-2.205211,-1.935489,1.852782,46.087094,20.0
1,Albania,ALB,11377.775743,2.215874,10.6890,79.776,108.355392,100.0,95.119427,99.299715,0.312344,0.020467,-0.118502,28.791971,15.707004,41.9
2,Algeria,DZA,5752.990767,4.046115,11.6550,76.475,105.164132,100.0,92.420029,85.906486,-0.251191,-0.693588,-0.696777,0.830314,25.552656,0.1
3,American Samoa,ASM,18017.458938,3.117464,5.1895,72.992,92.659564,100.0,100.000000,62.119698,0.767382,1.253029,1.086581,85.200000,6.715147,0.4
4,Andorra,AND,49303.649167,3.117464,5.1895,84.188,101.923820,100.0,100.000000,100.000000,1.159037,1.543796,1.409905,34.042553,9.080281,18.7

## 2. Select indicators

In [2]:
indicator_cols = [
    "gdp_per_capita",
    "inflation",
    "unemployment_rate",
    "life_expectancy",
    "secondary_enrollment",
    "electricity_access",
    "drinking_water_access",
    "sanitation_access",
    "government_effectiveness",
    "political_stability",
    "rule_of_law",
    "forest_area",
    "pm25_exposure",
    "renewable_energy"
]

## 3. Define positive and negative indicators

In [3]:
positive_indicators = [
    "gdp_per_capita",
    "life_expectancy",
    "secondary_enrollment",
    "electricity_access",
    "drinking_water_access",
    "sanitation_access",
    "government_effectiveness",
    "political_stability",
    "rule_of_law",
    "forest_area",
    "renewable_energy"
]

In [4]:
negative_indicators = [
    "inflation",
    "unemployment_rate",
    "pm25_exposure"
]

## 4. Apply Min-Max Normalisation

In [5]:
slqi_normalised_dataset = slqi_dataset.copy()

Positive indicators formula
(value - min) / (max - min)
Negative indicators formula
(max - value) / (max - min)

In [6]:
# Normalise positive indicators
for col in positive_indicators:
    min_value = slqi_normalised_dataset[col].min()
    max_value = slqi_normalised_dataset[col].max()
    
    slqi_normalised_dataset[col + "_normalised"] = (
        (slqi_normalised_dataset[col] - min_value) / (max_value - min_value)
    )

# Normalise negative indicators
for col in negative_indicators:
    min_value = slqi_normalised_dataset[col].min()
    max_value = slqi_normalised_dataset[col].max()
    
    slqi_normalised_dataset[col + "_normalised"] = (
        (max_value - slqi_normalised_dataset[col]) / (max_value - min_value)
    )

## 5. Check normalised values

In [ ]:
normalised_cols = [col + "_normalised" for col in indicator_cols]
slqi_normalised_dataset[normalised_cols].head()

,gdp_per_capita_normalised,inflation_normalised,unemployment_rate_normalised,life_expectancy_normalised,secondary_enrollment_normalised,electricity_access_normalised,drinking_water_access_normalised,sanitation_access_normalised,government_effectiveness_normalised,political_stability_normalised,rule_of_law_normalised,forest_area_normalised,pm25_exposure_normalised,renewable_energy_normalised
0,0.000675,0.975468,0.607191,0.365765,0.362540,0.844609,0.701991,0.492380,0.053644,0.125863,0.063870,0.019617,0.486559,0.207684
1,0.038774,0.937493,0.694057,0.789059,0.676600,1.000000,0.924119,0.992188,0.558159,0.639530,0.493751,0.304846,0.865235,0.435099
2,0.019228,0.929611,0.666068,0.685456,0.656038,1.000000,0.882150,0.842781,0.431593,0.474732,0.356937,0.008791,0.742513,0.001038
3,0.061846,0.933610,0.853403,0.576141,0.575467,1.000000,1.000000,0.577428,0.660358,0.923995,0.778862,0.902088,0.977315,0.004154
4,0.170560,0.933610,0.853403,0.927531,0.635160,1.000000,1.000000,1.000000,0.748322,0.991101,0.855357,0.360439,0.947834,0.194185

In [8]:
slqi_normalised_dataset[normalised_cols].describe()

,gdp_per_capita_normalised,inflation_normalised,unemployment_rate_normalised,life_expectancy_normalised,secondary_enrollment_normalised,electricity_access_normalised,drinking_water_access_normalised,sanitation_access_normalised,government_effectiveness_normalised,political_stability_normalised,rule_of_law_normalised,forest_area_normalised,pm25_exposure_normalised,renewable_energy_normalised
count,206.000000,206.000000,206.000000,206.000000,206.000000,206.000000,206.000000,206.000000,206.000000,206.000000,206.000000,206.000000,206.000000,206.000000
mean,0.075410,0.912850,0.808789,0.598898,0.554343,0.869615,0.858114,0.790878,0.499064,0.629091,0.510885,0.343798,0.768333,0.311849
std,0.119438,0.092381,0.155616,0.224465,0.156394,0.240783,0.211171,0.280615,0.217080,0.230300,0.239825,0.253868,0.183907,0.281637
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.008820,0.926898,0.761155,0.434938,0.523073,0.863636,0.816267,0.686989,0.335282,0.492630,0.316692,0.122147,0.694133,0.091641
50%,0.027296,0.933610,0.853403,0.613228,0.575467,1.000000,0.954859,0.921815,0.490261,0.638491,0.487636,0.343397,0.811366,0.219626
75%,0.100955,0.938099,0.904956,0.763725,0.634596,1.000000,0.996272,0.988542,0.646307,0.816597,0.691884,0.526493,0.905249,0.492212
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [9]:
slqi_normalised_dataset.to_csv("../Dataset/normalised_SLQI_dataset.csv", index=False)